name: Build Flutter AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.4'
          channel: 'stable'
          cache: false

      - name: Install Dependencies & Launcher Icons
        run: |
          flutter pub get
          dart run flutter_launcher_icons
      
      - name: Decode Keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/splitpe-keystore.jks

      # ----------------------------------------------------
      # প্লে স্টোরের জন্য AAB বিল্ড করার অংশ (সরাসরি সিক্রেট পাস করা হচ্ছে)
      # ----------------------------------------------------
      - name: Build App Bundle (AAB)
        env:
          KEYSTORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          flutter build appbundle --release \
            --dart-define=KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD"

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab