name: Build Flutter AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.4'
          channel: 'stable'
          cache: false

      - name: Install Dependencies & Launcher Icons
        run: |
          flutter pub get
          dart run flutter_launcher_icons
      - name: Decode Keystore and Create key.properties
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/splitpe-keystore.jks
          echo "storeFile=upload-keystore.jks" >> android/app/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/app/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/app/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/app/key.properties

      # ----------------------------------------------------
      # প্লে স্টোরের জন্য AAB বিল্ড করার অংশ (বর্তমানে চালু আছে)
      # ----------------------------------------------------
      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab


      # ----------------------------------------------------
      # APK বিল্ড করার অংশটি কমেন্ট করে রাখা হলো 
      # ----------------------------------------------------
      # - name: Build APK for Testing
      #   run: flutter build apk --release

      # - name: Upload APK Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release-aab
      #     path: build/app/outputs/flutter-apk/app-release.apk